trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:

- task: TerraformInstaller@1
  inputs:
    terraformVersion: '1.5.0'

- task: AzureCLI@2
  inputs:
    azureSubscription: 'azure-service-connection'  # 👈 replace this
    scriptType: bash
    scriptLocation: inlineScript
    inlineScript: |
      echo "Logged into Azure"
      az account show

      terraform init
      terraform plan -out=tfplan
      terraform apply -auto-approve tfplan
